# Generated by Django 5.2.7 on 2026-08-26 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dish',
        ),
    ]
